deploy:
    stage: deploy
    environment:
        name: review/environment
        auto_stop_in: 5 minutes
        on_stop: stop_app
    script:
        - echo "No commit"

stop_app:
    stage: deploy
    script:
        - echo
    environment:
        name: review/environment
        action: stop
    when: manual
