deploy:
    stage: deploy
    environment:
        name: review/environment
        auto_stop_in: 10 minutes
        on_stop: stop_app
    script:
        - echo "No commit" # No comment

stop_app:
    stage: deploy
    script:
        - echo '/** No comment **/' # Further no comment
    environment:
        name: review/environment
        action: stop
    when: manual
